version: '3'
services:
    website:
        container_name: website
        build: '.'
        env_file: .env
        ports:
            - '7000:80'
        volumes:
            - './clf:/app/clf'
        